
name: 'Build Corne Choc Pro BT'
on:
  workflow_dispatch:
    inputs:
      alphas:
        description: 'Alpha layout'
        required: true
        default: 'QWERTY'
        type: choice
        options:
          - 'AZERTY'
          - 'BEAKL15'
          - 'Colemak'
          - 'ColemakDH'
          - 'ColemakDHK'
          - 'Dvorak'
          - 'Halmak'
          - 'QWERTY'
          - 'QWERTZ'
          - 'Workman'
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corne_choc_pro_left","corne_choc_pro_right"]'
      extra_shield: '["sharp_mip"]'
      alphas: ${{ format('["{0}"]', inputs.alphas) }}
